//! Candidate transport help preserves the ordinary CLI surface.
cfg_if::cfg_if! {
    if #[cfg(all(unix, gwz_transport_candidate))] {
        pub(super) const JOBS_HELP: &str = "Global ceiling on concurrent member operations (default 100; 50 with --transport native)";
        pub(super) const JOBS_LONG_HELP: &str = "Global ceiling on the total number of member repositories processed concurrently across all hosts. These are concurrent operations in this process, not extra processes. Defaults to 100; 50 with --transport native. The smallest value is 1. 0 is rejected. Per-host concurrency is bounded separately by --max-per-host. Values above 100 are accepted.";
        pub(super) const MAX_PER_HOST_HELP: &str = "Max concurrent member operations to any one hostname (default 32; 8 with --transport native)";
        pub(super) const MAX_PER_HOST_LONG_HELP: &str = "Maximum concurrent member operations against one remote hostname. The hostname is the host in the remote URL, lowercased, before SSH config is applied. Two URLs share this limit when they contain the same host. A URL whose host cannot be parsed is bounded only by --jobs. Defaults to 32; 8 with --transport native. The smallest value is 1. 0 is rejected. Values above 32 are accepted. Each of these operations uses one connection.";
        pub(super) const VERBOSE_HELP: &str = "Show transport authentication diagnostics";
        pub(super) const VERBOSE_LONG_HELP: &str = "Show one transport diagnostic for every remote authentication attempt. These diagnostics are omitted from normal human output and remain available in --json and --jsonl output. It also names the transport selected for network operations, gwz or native, and what selected it. Authentication rows (meta.transport in JSON) are reported on either transport.";
        pub(super) const SSH_TIMEOUT_HELP: &str = "Per-attempt stall limit for setup and for a body read; stalled setup is retried (0 = no timeout, default 9; 3 with --transport native)";
        pub(super) const SSH_TIMEOUT_LONG_HELP: &str = "Seconds without progress before that read fails. The clock applies to SSH setup, and it applies to a stalled read during a fetch, push, or pull body on SSH and HTTPS. A body stall aborts that repository and is not retried. A setup stall fails one attempt, and that attempt is retried. HTTPS setup has no stall clock, only the 30 second setup budget that SSH setup also has. libssh2 has no timeout by default, so a missing ssh-agent identity or an unreachable host would otherwise hang forever. 0 disables this stall clock and the 30 second setup budget on both SSH and HTTPS. It does not disable retries. Defaults to 9. Retries are controlled by --max-retries (default 3 extra attempts). The wait after a failed setup attempt starts at 1 second and doubles, and does not grow past 30 seconds, plus up to 0.25 seconds of jitter. That wait is not this flag. At these defaults, an SSH setup that makes no progress is reported after at most 4 times 9 seconds plus 1, 2, and 4 seconds of waits and under 1 second of jitter, about 44 seconds, and an HTTPS setup that makes no progress after 4 times 30 seconds plus the same waits, about 128 seconds. A setup that keeps making progress but never finishes can use the 30 second budget on each attempt, about 128 seconds. A host-key prompt can add up to 120 seconds on each attempt. With --transport native it is instead libgit2's connect and read timeout, with no setup retry and no 30 second setup budget, and it defaults to 3, as in gwz 1.0.";
    } else {
        pub(super) const JOBS_HELP: &str = "Global ceiling on concurrent member operations (default 100)";
        pub(super) const JOBS_LONG_HELP: &str = "Global ceiling on the total number of member repositories processed concurrently across all hosts. These are concurrent operations in this process, not extra processes. Defaults to 100. The smallest value is 1. 0 is rejected. Per-host concurrency is bounded separately by --max-per-host. Values above 100 are accepted.";
        pub(super) const MAX_PER_HOST_HELP: &str = "Max concurrent member operations to any one hostname (default 32)";
        pub(super) const MAX_PER_HOST_LONG_HELP: &str = "Maximum concurrent member operations against one remote hostname. The hostname is the host in the remote URL, lowercased, before SSH config is applied. Two URLs share this limit when they contain the same host. A URL whose host cannot be parsed is bounded only by --jobs. Defaults to 32. The smallest value is 1. 0 is rejected. Values above 32 are accepted. Each of these operations uses one connection.";
        pub(super) const VERBOSE_HELP: &str = "Show transport authentication diagnostics";
        pub(super) const VERBOSE_LONG_HELP: &str = "Show one transport diagnostic for every remote authentication attempt. These diagnostics are omitted from normal human output and remain available in --json and --jsonl output.";
        pub(super) const SSH_TIMEOUT_HELP: &str = "Per-attempt stall limit for SSH setup and for a body read; stalled setup is retried (0 = no timeout, default 9)";
        pub(super) const SSH_TIMEOUT_LONG_HELP: &str = "Seconds without progress before that read fails. The clock applies to SSH setup, and it applies to a stalled read during a fetch, push, or pull body on SSH and HTTPS. A body stall aborts that repository and is not retried. A setup stall fails one attempt, and that attempt is retried. HTTPS setup has no stall clock, only the 30 second setup budget that SSH setup also has. libssh2 has no timeout by default, so a missing ssh-agent identity or an unreachable host would otherwise hang forever. 0 disables this stall clock and the 30 second setup budget on both SSH and HTTPS. It does not disable retries. Defaults to 9. Retries are controlled by --max-retries (default 3 extra attempts). The wait after a failed setup attempt starts at 1 second and doubles, and does not grow past 30 seconds, plus up to 0.25 seconds of jitter. That wait is not this flag. At these defaults, an SSH setup that makes no progress is reported after at most 4 times 9 seconds plus 1, 2, and 4 seconds of waits and under 1 second of jitter, about 44 seconds, and an HTTPS setup that makes no progress after 4 times 30 seconds plus the same waits, about 128 seconds. A setup that keeps making progress but never finishes can use the 30 second budget on each attempt, about 128 seconds. A host-key prompt can add up to 120 seconds on each attempt.";
    }
}
