use clap::{Command, CommandFactory};

use crate::Cli;

const DOCS_URL: &str = "https://owebeeone.github.io/gwz-cli/";
const GENERATOR_COMMAND: &str = "python scripts/generate_cli_reference.py --write";
const CHECK_COMMAND: &str = "python scripts/generate_cli_reference.py --check";
const TERM_WIDTH: usize = 100;

pub fn cli_reference_markdown() -> String {
    let command_paths = explicit_command_paths();
    let mut output = String::new();

    output.push_str("<!-- @generated by ");
    output.push_str(GENERATOR_COMMAND);
    output.push_str(" -->\n");
    output.push_str("# CLI Reference\n\n");
    output.push_str(
        "This reference is generated from the Clap command definitions used by the `gwz` binary.\n",
    );
    output.push_str("Do not hand-edit mechanical help content in this file; update the parser/help text and regenerate it.\n\n");
    output.push_str("Regenerate:\n\n");
    output.push_str("```sh\n");
    output.push_str(GENERATOR_COMMAND);
    output.push_str("\n```\n\n");
    output.push_str("Check for drift:\n\n");
    output.push_str("```sh\n");
    output.push_str(CHECK_COMMAND);
    output.push_str("\n```\n\n");
    output.push_str("Hosted docs: ");
    output.push_str(DOCS_URL);
    output.push_str("\n\n");

    output.push_str("## Root Help\n\n");
    push_help_block(&mut output, &[]);

    output.push_str("## Command Help\n\n");
    for path in command_paths {
        output.push_str("### `gwz ");
        output.push_str(&path.join(" "));
        output.push_str("`\n\n");
        if let Some(page) = command_page(&path) {
            output.push_str("Command page: [");
            output.push_str(page);
            output.push_str("](commands/");
            output.push_str(page);
            output.push_str(".md).\n\n");
        }
        push_help_block(&mut output, &path);
    }

    ensure_single_trailing_newline(&output)
}

fn explicit_command_paths() -> Vec<Vec<String>> {
    let command = Cli::command();
    let mut paths = Vec::new();
    collect_command_paths(&command, &mut Vec::new(), &mut paths);
    paths
}

fn collect_command_paths(
    command: &Command,
    prefix: &mut Vec<String>,
    paths: &mut Vec<Vec<String>>,
) {
    for subcommand in command.get_subcommands() {
        if subcommand.get_name() == "help" {
            continue;
        }
        prefix.push(subcommand.get_name().to_owned());
        paths.push(prefix.clone());
        collect_command_paths(subcommand, prefix, paths);
        prefix.pop();
    }
}

fn push_help_block(output: &mut String, path: &[String]) {
    output.push_str("```text\n");
    output.push_str(&render_help(path));
    output.push_str("```\n\n");
}

fn render_help(path: &[String]) -> String {
    let mut command = Cli::command().term_width(TERM_WIDTH);
    command.build();
    let command = command_for_path_mut(&mut command, path);
    let rendered = command.render_long_help().to_string();
    normalize_help_text(&rendered.replace("\r\n", "\n"))
}

fn command_for_path_mut<'a>(command: &'a mut Command, path: &[String]) -> &'a mut Command {
    let mut current = command;
    for segment in path {
        current = current
            .find_subcommand_mut(segment)
            .unwrap_or_else(|| panic!("missing Clap command path segment `{segment}`"));
    }
    current
}

fn normalize_help_text(input: &str) -> String {
    let mut normalized = String::new();
    for line in input.trim_end_matches('\n').lines() {
        normalized.push_str(line.trim_end());
        normalized.push('\n');
    }
    normalized
}

fn ensure_single_trailing_newline(input: &str) -> String {
    let trimmed = input.trim_end_matches('\n');
    format!("{trimmed}\n")
}

fn command_page(path: &[String]) -> Option<&'static str> {
    match path.first().map(String::as_str) {
        Some("add") => Some("add"),
        Some("branch") => Some("branch"),
        Some("capture") => Some("capture"),
        Some("clone") => Some("clone"),
        Some("commit") => Some("commit"),
        Some("diff") => Some("diff"),
        Some("forall") => Some("forall"),
        Some("init") => Some("init"),
        Some("ls") => Some("ls"),
        Some("materialize") => Some("materialize"),
        Some("pull") => Some("pull"),
        Some("push") => Some("push"),
        Some("repo") => Some("repo"),
        Some("snapshot") => Some("snapshot"),
        Some("stash") => Some("stash"),
        Some("status") => Some("status"),
        Some("tag") => Some("tag"),
        _ => None,
    }
}
